@startuml Semuwainn
  entity Reservation {
    * id
    __
    * reservation_time
    * reservation_number
    * check_in
    * check_out
    * guest_count
    discount
    * user_id
    * guest_id
    * reservation_status_id
  }

  entity ReservationStatus {
    * id
    __
    * name
  }

  entity RoomOrder {
    * id
    __
    * order_time
    * price
    * user_id
    * room_id
    * reservation_id
  }

  entity ServiceOrder {
    * id
    __
    * order_time
    * price
    * quantity
    discount
    * user_id
    * reservation_id
    * service_id
  }

  entity Service {
    * id
    __
    * name
    * price
    * unit
  }

  entity Guest {
    * id
    __
    * nik
    * name
    * phone
    email
  }

  entity User {
    * id
    __
    * name
    * phone
    * email
    * address
    * status
    * password
    * role_id
  }

  entity Role {
    * id
    __
    * name
  }

  entity RestaurantOrder {
    * id
    __
    * order_time
    * price
    * quantity
    discount
    * user_id
    * reservation_id
    * restaurant_id
  }

  entity Restaurant {
    * id
    __
    * name
    * price
    * unit
  }

  entity RoomFacility {
    * id
    __
    * room_type_id
    * facility_id
  }

  entity Room {
    * id
    __
    * room_number
    * room_type_id
  }

  entity RoomType {
    * id
    __
    * name
    * number_of_guest_id
  }

  entity RoomPrice {
    * id
    __
    * description
    * price
    * room_type_id
  }

  entity Facility {
    * id
    __
    * name
  }

  entity NumberOfGuest {
    * id
    __
    * guest
  }

  Reservation ||--|{ ReservationStatus
  Reservation }|--|| RestaurantOrder
  Reservation }|--|| ServiceOrder
  Reservation ||--|{ User
  Reservation ||--|{ Guest
  Reservation }|--|| RoomOrder
  RoomOrder ||--|{ User
  RoomOrder ||--|{ Room
  Room ||-|{ RoomType
  RoomType }|--|| RoomPrice
  RoomType }|--|| RoomFacility
  RoomType ||--|{ NumberOfGuest
  RoomFacility ||--|{ Facility
  ServiceOrder ||--|{ Service
  RestaurantOrder ||--|{ Restaurant
  User ||--|{ Role
  ServiceOrder ||--|{ User
  RestaurantOrder ||--|{ User

@enduml
